- id: standardrb
  name: Check Ruby files with StandardRB
  description: Standard - Ruby style guide, linter, and formatter
  entry: standardrb
  pass_filenames: true
  language: ruby
  types: ["ruby"]
